# Configuration file for codecov reporting code coverage

# Percentage drop allowed
coverage:
  status:
    project:
      default:
        # base on last build, but allow drop of upto this percent
        target: 80.0
        threshold: 2.0
